@host = http://localhost:5114

GET {{host}}/api/weatherforecast/
Accept: application/json

###
@id = 1

GET {{host}}/api/hotel/gethotels
Accept: application/json

###
GET {{host}}/api/hotel/gethotel/{{id}}
Accept: application/json

###
POST {{host}}/api/hotel/createhotel
Content-Type: application/json  

{
    "name": "Hotel California",
    "address": "42 Sunset Boulevard",
    "countryId": 1,
    "rating": 4.5
}

###
PUT {{host}}/api/hotel/updatehotel/{{id}}
Content-Type: application/json  

{
    "name": "Hotel California Updated",
    "address": "42 Sunset Boulevard",
    "country": "USA",
    "rating": 4.7
}

###
DELETE {{host}}/api/hotel/deletehotel/{{id}} 

### Note: Replace {{id}} with the actual hotel ID you want to retrieve, update, or delete.
GET {{host}}/api/country/getcountries
Accept: application/json

###
GET {{host}}/api/country/getcountry/{{id}}
Accept: application/json

###
POST {{host}}/api/country/createcountry
Content-Type: application/json

{
    "name": "Spain",
    "code": "ES"
}

###
PUT {{host}}/api/country/updatecountry/{{id}}
Content-Type: application/json

{
    "name": "India",
    "code": "IN"
}

###
DELETE {{host}}/api/country/deletecountry/{{id}}


